name: TEST_PDBL_WEBSTRESS

on:
  repository_dispatch:
    types:
      - pdbl_webstreet
  #schedule:
    # 此处是UTC时间，对应北京时间早八点
    # - cron : '00 04 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Stress Test
      run: |
        wget -q https://github.com/link1st/go-stress-testing/releases/download/v1.0.8/go-stress-testing-linux -O gostress
        chmod +x gostress
        ./gostress -c 1000 -n 100000 -u $DBL_IMAGES_URL1 2>&1 > /dev/null
        ./gostress -c 1000 -n 100000 -u $DBL_IMAGES_URL2 2>&1 > /dev/null
        ./gostress -c 1000 -n 100000 -u $DBL_IMAGES_URL3 2>&1 > /dev/null
        ./gostress -c 1000 -n 100000 -u $DBL_IMAGES_URL4 2>&1 > /dev/null
      env:
        DBL_IMAGES_URL1: ${{ vars.DBL_IMAGES_URL1 }}
        DBL_IMAGES_URL2: ${{ vars.DBL_IMAGES_URL2 }}
        DBL_IMAGES_URL3: ${{ vars.DBL_IMAGES_URL3 }}
        DBL_IMAGES_URL4: ${{ vars.DBL_IMAGES_URL4 }}
