name: TEST_PDBL_WEBSTRESS

on:
  repository_dispatch:
    types:
      - pdbl_webstreet
  schedule:
    # 此处是UTC时间，对应北京时间早八点
    - cron : '00 23 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Siege
      run: |
        sudo echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy main restricted universe multiverse" > /etc/apt/source.list && \
        sudo apt update && \
        sudo apt install -y siege && \
        which siege && \
        siege --version
    - name: Stress Test
      run: |
        echo $DBL_IMAGES_URL > images.txt && \
        cat images.txt
      env:
        DBL_IMAGES_URL: ${{ vars.DBL_IMAGES_URL }}
